### ISSUE TITLE
Where is the license file of this repo?

### ISSUE THREAD

**Issue by kuslahne** [BakhadyrovF/Authorisation-w-PHP-MySql#1]
Hi BakhadyrovF,

Thank you for created this repository. I need to know if this repo is open source? Please include the license file.
Can I use this for private project or  for commercial ? 

Thank you,
Kus

**Comment by BakhadyrovF** [comment]
Hi, repo is open-source do not worry about this, of course you can use this.

**Comment by kuslahne** [comment]
Thank you for your kindness @BakhadyrovF. I am happy to hear that.
